### ISSUE TITLE
Sync Branches doesn't work

### ISSUE THREAD

**Issue by mariotux** [mjdetullio/multi-branch-project-plugin#107]
I've 0.3 version and when configure the multi-branch project doesn't work in sync action. This is the log of this.

Started on Oct 14, 2015 2:02:00 PM
Setting origin to ******
Fetching origin...
FATAL: Could not initialize class org.eclipse.jgit.transport.Transport
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.transport.Transport
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:120)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:672)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:171)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:141)
	at jenkins.scm.api.SCMSource.retrieve(SCMSource.java:180)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:167)
	at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject._syncBranches(AbstractMultiBranchProject.java:981)
	at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject.syncBranches(AbstractMultiBranchProject.java:948)
	at com.github.mjdetullio.jenkins.plugins.multibranch.SyncBranchesTrigger.run(SyncBranchesTrigger.java:102)
	at com.github.mjdetullio.jenkins.plugins.multibranch.SyncBranchesTrigger.checkTriggers(SyncBranchesTrigger.java:255)
	at com.github.mjdetullio.jenkins.plugins.multibranch.SyncBranchesTrigger$Cron.doRun(SyncBranchesTrigger.java:230)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Done. Took 89 ms

**Comment by mjdetullio** [comment]
This is probably a class loading problem with the Git Plugin, which uses JGit as a dependency.  Try restarting Jenkins.

**Comment by mjdetullio** [comment]
Or a bug with the Git Plugin possibly introduced by changing the JGit version

**Comment by mariotux** [comment]
I can use git plugin in a jenkins project, but when i try to create a multi-branch project I've this error, what is the problem?

**Comment by mjdetullio** [comment]
I don't know.  Look at the stack trace.  Multi-branch project calls the SCMSource API, that API calls the Git Plugin, Git Plugin uses JGit, something fails because a class is missing.  Either the class is there and was not loaded properly by Jenkins, or the Git Plugin does not properly define all dependencies and so the class really is missing.

**Comment by mariotux** [comment]
Try to upgrade any jenkins who you has multi-branch installed, you will have the same problem

**Comment by mariotux** [comment]
In the last version of jenkins (1.634) work fine

**Comment by timomayer** [comment]
but this version seems not available in jenkins debian repositories jet :( i have installed the repository but with apt-get i still only get 1.633

**Comment by mariotux** [comment]
@timomayer I have installed in debian from jenkins repositories.
deb http://pkg.jenkins-ci.org/debian binary/
