### ISSUE TITLE
Upgrading to 0.4.1 seems to have broken 0.3 builds

### ISSUE THREAD

**Issue by stephenh** [mjdetullio/multi-branch-project-plugin#130]
After upgrading to the refactored 0.4.1, executors started failing with:

```
java.lang.IllegalStateException: /mnt/hudson/jobs/my-job-ci/branches/branch-foo/builds/1 already existed; will not overwrite with my-job-ci/branch-foo #1
	at hudson.model.RunMap.put(RunMap.java:188)
	at jenkins.model.lazy.LazyBuildMixIn.newBuild(LazyBuildMixIn.java:176)
	at hudson.model.AbstractProject.newBuild(AbstractProject.java:1019)
	at hudson.model.AbstractProject.createExecutable(AbstractProject.java:1210)
	at hudson.model.AbstractProject.createExecutable(AbstractProject.java:145)
	at hudson.model.Executor$1.call(Executor.java:364)
	at hudson.model.Executor$1.call(Executor.java:346)
	at hudson.model.Queue._withLock(Queue.java:1402)
	at hudson.model.Queue.withLock(Queue.java:1267)
	at hudson.model.Executor.run(Executor.java:346)
```

Downgrading back to 0.3 fixed it. My random guess based on this bug report:

https://issues.jenkins-ci.org/browse/JENKINS-29902

Is that maybe in the refactoring to the CustomFolder-based implementation, the somehow existing build numbers got lost, and all child branches tried to start over at 1? But then that failed since they had already been built?

I did not think of deleting the "my-job" multi-branch job and just starting from scratch. If I get curious, I might try it again, but for now am going to stay on 0.3.

**Comment by mjdetullio** [comment]
I hadn't noticed the issue during my upgrade testing.  As the issue
mentions, I have personally seen problems with attempting to overwrite
build numbers but only when reloading configuration from disk when builds
were running and in queue.

If you can give steps to reproduce on a fresh Jenkins install it would be
helpful.

**Comment by stephenh** [comment]
Huh. I re-upgraded and it's working just fine now; I wonder if it was because, before upgrading the 1st time, the "branch sync" seemed to be stuck (it had hung for ~days, and new branches weren't showing up), and after upgrading+restarting, a whole bunch of branches (maybe all?, not sure) entered the build queue. But none of them could actually build, due to that stack trace.

But now things are fine...I think. I do see this output in the sync log:

```
Syncing config from template to branch branch-foo
FATAL: Failed to persist config.xml
java.io.IOException: Failed to persist config.xml
	at hudson.model.AbstractItem.updateByXml(AbstractItem.java:645)
	at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject.computeChildren(AbstractMultiBranchProject.java:609)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:151)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:106)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.xml.sax.SAXException: SAX2 driver class org.apache.xerces.parsers.SAXParser not found
java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:230)
	at org.xml.sax.helpers.XMLReaderFactory.createXMLReader(XMLReaderFactory.java:191)
	at jenkins.util.xml.XMLUtils.safeTransform(XMLUtils.java:48)
	at hudson.model.AbstractItem.updateByXml(AbstractItem.java:640)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:430)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at org.xml.sax.helpers.NewInstance.newInstance(NewInstance.java:82)
	at org.xml.sax.helpers.XMLReaderFactory.loadClass(XMLReaderFactory.java:228)
	... 8 more
```

...okay, looks like this is a known issue:

https://issues.jenkins-ci.org/browse/JENKINS-27548

Since 0.4.1 seems to be working fine now, and you verified it works for you, sounds like this was just a fluke. Thanks for the quick response!
