### ISSUE TITLE
org.eclipse.jgit.api.errors.TransportException when sync branches

### ISSUE THREAD

**Issue by pedroluislopez** [mjdetullio/multi-branch-project-plugin#133]
Jenkins: 1.642
GIT client plugin: 1.19.0
GIT plugin: 2.4.0
Matrix Authorization Strategy Plugin: 1.2
Multi-Branch Project Plugin: 0.4.1
SCM API Plugin: 1.0

```Setting origin to git@git.compraactiva.me:plopez/sense.git
Fetching origin...
FATAL: Failed to recompute children of Sync Branches
hudson.plugins.git.GitException: org.eclipse.jgit.api.errors.TransportException: git@git.compraactiva.me:plopez/sense.git: Failed to connect
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:674)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:171)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:143)
	at jenkins.scm.api.SCMSource.retrieve(SCMSource.java:219)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:169)
	at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject.computeChildren(AbstractMultiBranchProject.java:582)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:151)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:106)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.eclipse.jgit.api.errors.TransportException: git@git.compraactiva.me:plopez/sense.git: Failed to connect
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:139)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:672)
	... 9 more
Caused by: org.eclipse.jgit.errors.TransportException: git@git.compraactiva.me:plopez/sense.git: Failed to connect
	at org.jenkinsci.plugins.gitclient.trilead.TrileadSessionFactory.getSession(TrileadSessionFactory.java:54)
	at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	... 10 more
Caused by: java.io.IOException: There was a problem while connecting to git.compraactiva.me:22
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:587)
	at org.jenkinsci.plugins.gitclient.trilead.TrileadSessionFactory.getSession(TrileadSessionFactory.java:29)
	... 17 more
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:93)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:230)
	at com.trilead.ssh2.Connection.connect(Connection.java:770)
	... 20 more
Caused by: java.io.IOException: Cannot negotiate, proposals do not match.
	at com.trilead.ssh2.transport.KexManager.handleMessage(KexManager.java:405)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:777)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:489)
	at java.lang.Thread.run(Thread.java:745)
Finished: FAILURE```

**Comment by pedroluislopez** [comment]
```# java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1~deb8u1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)```

**Comment by mjdetullio** [comment]
Please use the Jenkins users mailing list for troubleshooting or file your bug against the Git Plugin.  This plugin does not have any SCM connectivity code.
