### ISSUE TITLE
java.lang.IllegalStateException: Cannot open session, connection is not authenticated.

### ISSUE THREAD

**Issue by macq-npokrovskaya** [mjdetullio/multi-branch-project-plugin#17]
Hi, 
First of all, thank you for this plugin, it's really what we were looking for :+1: 
Probably, I misconfigured the plugin, because it fails on fetch...
When I use ssh connection for my repository, it fails on branches sync with:
```
Started on Nov 6, 2014 3:35:01 PM
Setting origin to ssh://git@dvcs.macqel/ebuttf/macqclient.git
Fetching origin...
FATAL: Cannot open session, connection is not authenticated.
java.lang.IllegalStateException: Cannot open session, connection is not authenticated.
	at com.trilead.ssh2.Connection.openSession(Connection.java:1128)
	at org.jenkinsci.plugins.gitclient.trilead.TrileadSession.exec(TrileadSession.java:24)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1115)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:495)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:170)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:141)
	at jenkins.scm.api.SCMSource.retrieve(SCMSource.java:180)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:167)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject._syncBranches(FreeStyleMultiBranchProject.java:1051)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject.syncBranches(FreeStyleMultiBranchProject.java:1018)
	at com.github.mjdetullio.jenkins.plugins.multibranch.SyncBranchesTrigger.run(SyncBranchesTrigger.java:98)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:266)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:317)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:150)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$101(ScheduledThreadPoolExecutor.java:98)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.runPeriodic(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:204)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Done. Took 0.36 sec
```

When I use HTTPS connection, branch sync works fine, but I have the following stacktrace...
```
Started by user anonymous
Building on master in workspace /var/lib/jenkins/jobs/macqclient2/branches/develop/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://jenkins@stash.macq.eu/scm/ebuttf/macqclient.git # timeout=10
Fetching upstream changes from https://jenkins@stash.macq.eu/scm/ebuttf/macqclient.git
 > git --version # timeout=10
FATAL: Failed to fetch from https://jenkins@stash.macq.eu/scm/ebuttf/macqclient.git
hudson.plugins.git.GitException: Failed to fetch from https://jenkins@stash.macq.eu/scm/ebuttf/macqclient.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:647)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:889)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:914)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1258)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:622)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
	at hudson.model.Run.execute(Run.java:1759)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleBranchBuild.run(FreeStyleBranchBuild.java:89)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: hudson.plugins.git.GitException: Failed to connect to https://jenkins@stash.macq.eu/scm/ebuttf/macqclient.git using credentials Stash jenkins (status = 401)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.checkCredentials(CliGitAPIImpl.java:2247)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1169)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:85)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:280)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:645)
	... 10 more
```

I verified the credentials and they're OK.

Have I missed something in configuration?

thank you in advance for your help!

**Comment by macq-npokrovskaya** [comment]
@mjdetullio  thank you for your reply.
For SSH, we don't use credentials, we are working with ssh autorized keys, that's why, I suppose, I have "not authenticated" exception. But it works for all others "not multi-branch" items on Jenkins. Is there a workaround for this problem?
Thank you in advance!

**Comment by loucasa** [comment]
I have the same issue, using ssh authorized keys too. Other builds work fine with the same settings seems like this plugin does not use the key for some reason

**Comment by IvanAnishchuk** [comment]
Same things here: works with https, doesn't work with ssh while same ssh configuration and url works with non-multi job.

(Repo is on Github, I should probably note, a private one. Latest available versions of Jenkins and the plugin and everything, on Ubuntu 14.04.)

It seems to me that the problem has something to do with the fact that multi-branch plugin uses JGit library to sync branches instead of git executable and that library pays no attentions to user's `.ssh` configuration and keys... But I'd like to hear the developers' opinion.

**Comment by mjdetullio** [comment]
Looks like some JGit references here https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java

**Comment by mjdetullio** [comment]
Looks like some JGit references here https://github.com/jenkinsci/git-plugin/blob/master/src/main/java/jenkins/plugins/git/AbstractGitSCMSource.java
