### ISSUE TITLE
Syncing from GIT doesn't work

### ISSUE THREAD

**Issue by Nemesis69** [mjdetullio/multi-branch-project-plugin#20]
Hello,

tired the plugin with GIT repository and got :
Pruning stale remotes...
Getting remote branches...
Checking branch portafixe
Met criteria
Checking branch G4R0C6
Met criteria
Checking branch master
Met criteria
Done.
Syncing configuration to project for branch G4R0C6
FATAL: null
java.lang.NullPointerException
	at hudson.plugins.disk_usage.DiskUsageUtil.loadData(DiskUsageUtil.java:84)
	at hudson.plugins.disk_usage.DiskUsageUtil.addProperty(DiskUsageUtil.java:64)
	at hudson.plugins.disk_usage.DiskUsageItemListener.onUpdated(DiskUsageItemListener.java:40)
	at hudson.model.listeners.ItemListener.fireOnUpdated(ItemListener.java:142)
	at hudson.model.AbstractProject.makeDisabled(AbstractProject.java:708)
	at hudson.model.AbstractProject.enable(AbstractProject.java:727)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject._syncBranches(FreeStyleMultiBranchProject.java:1107)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject.syncBranches(FreeStyleMultiBranchProject.java:1018)
	at com.github.mjdetullio.jenkins.plugins.multibranch.SyncBranchesTrigger.run(SyncBranchesTrigger.java:98)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:255)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:203)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Can't make it work and nothing is synced in sub projects.

Regards.

Nicolas.

**Comment by mjdetullio** [comment]
Appears to duplicate #2
