### ISSUE TITLE
Cannot open session, connection is not authenticated

### ISSUE THREAD

**Issue by galan** [mjdetullio/multi-branch-project-plugin#31]
Hi, seems like the plugin is not able to get the list of branches. We are using git over ssh:

```
Sync Branches Log

Started on Feb 18, 2015 8:24:00 AM
Setting origin to ssh://git@ourhost:12345/project.git
Fetching origin...
FATAL: Cannot open session, connection is not authenticated.
java.lang.IllegalStateException: Cannot open session, connection is not authenticated.
	at com.trilead.ssh2.Connection.openSession(Connection.java:1127)
	at org.jenkinsci.plugins.gitclient.trilead.TrileadSession.exec(TrileadSession.java:32)
	at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
	at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
	at org.jenkinsci.plugins.gitclient.JGitAPIImpl.fetch(JGitAPIImpl.java:637)
	at jenkins.plugins.git.AbstractGitSCMSource.retrieve(AbstractGitSCMSource.java:171)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:141)
	at jenkins.scm.api.SCMSource.retrieve(SCMSource.java:180)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:167)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject._syncBranches(FreeStyleMultiBranchProject.java:1051)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject.syncBranches(FreeStyleMultiBranchProject.java:1018)
	at com.github.mjdetullio.jenkins.plugins.multibranch.SyncBranchesTrigger.run(SyncBranchesTrigger.java:98)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:265)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:214)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Done. Took 0.1 sec

```

**Comment by galan** [comment]
Never mind, issue with credentials.

**Comment by hekaldama** [comment]
How did you fix?

**Comment by galan** [comment]
Sorry, I can't remember exactly, and since I'm not working in the company any longer, I'm unable to sneak what it might have been. However, I think I was either using the Jenkins credentials incorrect or did not setup the ssh for the jenkins user correctly.
