### ISSUE TITLE
Oops and stack trace with Jenkins 1.609

### ISSUE THREAD

**Issue by MarkEWaite** [mjdetullio/multi-branch-project-plugin#42]
I downloaded and executed the 1.609 (latest) jenkins.war, (java -jar jenkins.war --httpPort=9090) updated the plugins, and installed git client plugin, git plugin, findbugs plugin, and a few others. I installed the freestyle multibranch plugin, then stopped and restarted jenkins.

When I create a new freestyle multibranch job, an Oops screen appears on the configuration page with the following stack trace:

    Stack trace
    
    javax.servlet.ServletException: org.apache.commons.jelly.JellyTagException: jar:file:/C:/Users/waima04/.jenkins/plugins/multi-branch-project-plugin/WEB-INF/lib/classes.jar!/com/github/mjdetullio/jenkins/plugins/multibranch/AbstractMultiBranchProject/configure-entries.jelly:80:74: <st:include> No page found 'configure-branch-entries.jelly' for class hudson.model.FreeStyleProject
    	at org.kohsuke.stapler.jelly.JellyFacet$1.dispatch(JellyFacet.java:103)
    	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:249)
    	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
    	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:746)
    	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
    	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
    	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
    	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:123)
    	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:114)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:168)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
    	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
    	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
    	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
    	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
    	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    	at org.eclipse.jetty.server.Server.handle(Server.java:370)
    	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
    	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
    	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    	at java.lang.Thread.run(Unknown Source)
    Caused by: org.apache.commons.jelly.JellyTagException: jar:file:/C:/Users/waima04/.jenkins/plugins/multi-branch-project-plugin/WEB-INF/lib/classes.jar!/com/github/mjdetullio/jenkins/plugins/multibranch/AbstractMultiBranchProject/configure-entries.jelly:80:74: <st:include> No page found 'configure-branch-entries.jelly' for class hudson.model.FreeStyleProject
    	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:124)
    	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
    	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:95)
    	at org.kohsuke.stapler.jelly.IncludeTag.doTag(IncludeTag.java:147)
    	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
    	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
    	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
    	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
    	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
    	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.apache.commons.jelly.tags.core.CoreTagLibrary$1.run(CoreTagLibrary.java:98)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
    	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.CallTagLibScript$1.run(CallTagLibScript.java:99)
    	at org.apache.commons.jelly.tags.define.InvokeBodyTag.doTag(InvokeBodyTag.java:91)
    	at org.apache.commons.jelly.impl.TagScript.run(TagScript.java:269)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.kohsuke.stapler.jelly.ReallyStaticTagLibrary$1.run(ReallyStaticTagLibrary.java:99)
    	at org.apache.commons.jelly.impl.ScriptBlock.run(ScriptBlock.java:95)
    	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
    	at org.kohsuke.stapler.jelly.CallTagLibScript.run(CallTagLibScript.java:120)
    	at org.apache.commons.jelly.tags.core.CoreTagLibrary$2.run(CoreTagLibrary.java:105)
    	at org.kohsuke.stapler.jelly.JellyViewScript.run(JellyViewScript.java:95)
    	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:63)
    	at org.kohsuke.stapler.jelly.DefaultScriptInvoker.invokeScript(DefaultScriptInvoker.java:53)
    	at org.kohsuke.stapler.jelly.JellyFacet$1.dispatch(JellyFacet.java:95)
    	... 49 more

**Comment by mjdetullio** [comment]
Duplicate of #40
