### ISSUE TITLE
Exception when using EmailExt plugin in conjunction with MBPP

### ISSUE THREAD

**Issue by moshezvi** [mjdetullio/multi-branch-project-plugin#60]
May 26, 2015 11:39:36 AM hudson.model.AbstractProject createTransientActions
SEVERE: Could not load actions from hudson.plugins.emailext.EmailExtTemplateActionFactory@401c1b5f for com.github.mjdetullio.jenkins.plugins
.multibranch.FreeStyleMultiBranchProject@660f260[tests4]
java.lang.NullPointerException
        at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject.getPublishersList(AbstractMultiBranchProject.java:12
32)
        at hudson.plugins.emailext.EmailExtTemplateActionFactory.createFor(EmailExtTemplateActionFactory.java:27)
        at hudson.model.AbstractProject.createTransientActions(AbstractProject.java:759)
        at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject.createTransientActions(AbstractMultiBranchProject.ja
va:1263)
        at hudson.model.AbstractProject.updateTransientActions(AbstractProject.java:748)
        at hudson.model.AbstractProject.onLoad(AbstractProject.java:333)
        at com.github.mjdetullio.jenkins.plugins.multibranch.AbstractMultiBranchProject.onLoad(AbstractMultiBranchProject.java:158)
        at hudson.model.Items.load(Items.java:322)
        at jenkins.model.Jenkins$17.run(Jenkins.java:2655)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$7.runTask(Jenkins.java:905)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gmetal** [comment]
I am getting the same error. Have you managed to find a workaround for this?

**Comment by mjdetullio** [comment]
I think this may have been fixed in 0.3
