### ISSUE TITLE
java.lang.NoSuchMethodException: hudson.model.AbstractProject.convertUpstreamBuildTrigger(java.util.Set)

### ISSUE THREAD

**Issue by eshryane** [mjdetullio/multi-branch-project-plugin#7]
Using the latest Jenkins version (1.579), the multi-branch plugin fails with the following exception:

```
Sep 08, 2014 1:00:15 PM com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject doConfigSubmit
WARNING: Unable to execute convertUpstreamBuildTrigger(Set)
java.lang.NoSuchMethodException: hudson.model.AbstractProject.convertUpstreamBuildTrigger(java.util.Set)
	at java.lang.Class.getDeclaredMethod(Class.java:2004)
	at com.github.mjdetullio.jenkins.plugins.multibranch.FreeStyleMultiBranchProject.doConfigSubmit(FreeStyleMultiBranchProject.java:716)
...
```

This method call appears to have been removed from Jenkins on the 11th April, by this commit:

https://github.com/jenkinsci/jenkins/commit/840bb

**Comment by mjdetullio** [comment]
Fixed with 0.2 release
